apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.broker.service.name }}
spec:
  ports:
    - port: {{ .Values.broker.port }}
      name: broker
  clusterIP: None
  selector:
    app: kafka
    role: broker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.broker.statefulset.name }}
spec:
  serviceName: "broker"
  replicas: {{ .Values.broker.replicas }}
  ordinals:
    start: {{ .Values.broker.ordinals.start }}
  selector:
    matchLabels:
      app: kafka
      role: broker
  template:
    metadata:
      labels:
        app: kafka
        role: broker
    spec:
      containers:
        - name: kafka-broker
          image: apache/kafka:{{ .Values.kafka.version }}
          ports:
            - containerPort: {{ .Values.broker.port }}
              name: broker
          env:            
            - name: KAFKA_PROCESS_ROLES
              value: broker
            - name: KAFKA_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: {{ include "controller.quorum.voters" . }}
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER