apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ui.port }}
      name: webui
  selector:
    app: kafka
    role: kafka-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  selector:
    matchLabels:
      app: kafka
      role: kafka-ui
  template:
    metadata:
      labels:
        app: kafka
        role: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: {{ .Values.ui.port }}
              name: webui
          env:
            - name: SERVER_PORT
              value: "{{ .Values.ui.port }}"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: {{ include "bootstrap.servers" $ }}