spring:
  application:
    name: mqtt-sink-connector

  docker:
    compose:
      enabled: false

  kafka:
    consumer:
      group-id: mqtt-sink-connector

  profiles:
    group:
      local:
        - local-docker-compose
        - quote-msg-producer
    default: local
---
spring:
  config:
    activate:
      on-profile:
        - local-docker-compose
  
  docker:
    compose:
      enabled: true
      lifecycle-management: start-only
      start:
        command: start
        log-level: debug

  kafka:
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      # sasl.jaas.config should be in a single line or else may cause an exception
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='peter' password='peter-secret';
    #consumer:
    #  properties:
    #    security.protocol: SASL_PLAINTEXT
    #    sasl.mechanism: PLAIN